name: Pr Validtion workflow
run-name: PR title ${{ github.event.pull_request.title }} verifcation
on:
  pull_request:
   types: [opened, synchronize]
jobs:
  pr-validation:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Validation PR Title.."
      - uses: prilior/typescript-action@main
        with:
          ticketPrefix: "ABC"
          prTitle: "${{ github.event.pull_request.title }}"
              

            
      
    
